version: '3.7'

services:

  node:
    container_name: elibrary
    image: elibrary
    build:
      context: .
      args:
        PACKAGES: "nano wget curl"
    ports:
      - "8000:8000"
    networks:
      - elibrary-network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - elibrary-network

networks:
  elibrary-network:
    driver: bridge