name: pull request lint
on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [opened, edited, reopened]

jobs:
  commitLint:
    runs-on: ubuntu-latest
    env:
      ENV_PAT: ${{ secrets.ENV_PAT }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: linting
        uses: wagoid/commitlint-github-action@v5
