name: Send LGTM reaction
on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [opened, edited, reopened]

jobs:
  commitLint:
    runs-on: ubuntu-latest
    env:
      ENV_PAT: ${{ secrets.ENV_PAT }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: linting
        uses: wagoid/commitlint-github-action@v2

name: Send LGTM reaction
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-lgtm-reaction@master # Set some version.
    env:
      ENV_PAT: ${{ secrets.ENV_PAT }}
      GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
      with:
        trigger: '[".*looks good to me.*"]'
        override: true
        source: 'giphy'